### ISSUE TITLE
How long time it'll take for a 64G DDR test?

### ISSUE THREAD

**Issue by clockzhong** [jnavila/memtester#2]
Hi, Jean-Noël Avila,

You did a great job on this program, I used it and found my DDR problems. 
But I've one question or a new feature request.
Can you add time consumption percentage into the program? I've a 64G memory machine, and using your program to check the memory status, but it runned for serveral hours, and I don't know when it'll close.
If adding time consumption percentage information is too complex, can you tell me how to estimate the time consution based on the memory size we used?

Thanks in advance.

Clock Zhong

**Comment by clockzhong** [comment]
Jean-Noël Avila,
You could close this issue, I've found a way to calculate the work progress percentage now.
It's very simple, I just run "sudo memtester 1024 1", this is for 1G memory, and it takes about 5 minutes, then I could estimate the 64G memory could take about 5minutes*64=5.3 hours
Thanks!
Clock ZHONG

**Comment by jnavila** [comment]
I am not the original maintainer of the project. This repository is only a mirror of the history at  http://pyropus.ca/software/memtester/ . If you have added features, please send them to the maintainer.
