### ISSUE TITLE
[BUG] If you don't specify a physical address, and do_mlock is disabled, then aligned address is never set, causing segfault

### ISSUE THREAD

**Issue by keithgh1** [jnavila/memtester#3]
If you don't specify a physical address, and do_mlock is disabled, then aligned address is never set, causing segfault

The aligned address is either set when use_phys is true, or when there's an mlock attempt (when do_mlock is true).

If neither block of code runs, then both variables aligned and bufa are wrong. The result is the tests start writing to unsafe areas of memory!

A possible solution, which does function, is to move the alignment code outside of the "if (do_mlock) {}" block, like above it for instance.

**Comment by jnavila** [comment]
Thanks for your interest in memtester. This repo is only a mirror. As written in the README, the original project is developped at http://pyropus.ca/software/memtester/ and is accepting patches.

If you prefer, please submit a PR here and I'll push the patch upstream.

**Comment by jnavila** [comment]
Seems to be fixed with the latest v4.5.0 from pyropus.ca

**Comment by keithgh1** [comment]
Thanks @jnavila I worked directly with Charles at pyropus.ca to get the issues worked out. 4.4.0 had a big bug, but 4.5.0 should be humming along nicely!
