### ISSUE TITLE
[Feature request] Add ability to run specific tests

### ISSUE THREAD

**Issue by leinardi** [jnavila/memtester#5]
I'm using memtester to test the stability while tightening the timings of my RAM and I notice that almost always I get failures in the Block Sequential test.

It would be really useful to be able to run just this test multiple times since most of the other tests they never fail or fail not as often.

BTW, thanks for the awesome tool :+1: 

EDIT
As a workaround, I'm  commenting the test I don't want to run here:
https://github.com/jnavila/memtester/blob/c1acc5cb69419794402a75269fc988c86b091c0a/memtester.c#L37
and building the binary with `make`

**Comment by jnavila** [comment]
you can already mask some tests with the environment variable `MEMTESTER_TEST_MASK`. This is a bitmask of tests to skip in the order of appearance in the list.

Something like:
```bash
$ MEMTESTER_TEST_MASK=0xFFDF memtester
```
should only select Block Sequential.

**Comment by jnavila** [comment]
BTW, this tool is not mine. You can send your thanks to M. Charles Cazabon <charlesc-memtester@pyropus.ca> !

**Comment by leinardi** [comment]
Hey, one question: did something change recently with the test mask? Isn't working for me anymore:

```
$ MEMTESTER_TEST_MASK=0xFFDF /usr/sbin/memtester 4000 3
memtester version 4.3.0 (64-bit)
Copyright (C) 2001-2012 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 4096
pagesizemask is 0xfffffffffffff000
using testmask 0xffdf
want 4000MB (4194304000 bytes)
got  4000MB (4194304000 bytes), trying mlock ...locked.
Loop 1/3:
  Stuck Address       : ok         
  Random Value        : ok
  Compare XOR         : ok
  Compare SUB         : ok
  Compare MUL         : ok
  Compare DIV         : ok
  Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok         
  Block Sequential    : ok         
```

**Comment by jnavila** [comment]
It seems now the mask is inverted?

**Comment by leinardi** [comment]
Just for future reference, this is the mask for the Block Sequential for version 4.3.0:
```
MEMTESTER_TEST_MASK=0x200 memtester 4000 3
```
